status = [
    'integration-tests (PHP 7.4) (Symfony 5.4.*)',
    'integration-tests (PHP 8.1) (Symfony 6.4.*)',
    'integration-tests (PHP 8.2) (Symfony 6.4.*)',
    'integration-tests (PHP 8.3) (Symfony 6.4.*)',
    'integration-tests (PHP 8.2) (Symfony 7.0.*)',
    'integration-tests (PHP 8.3) (Symfony 7.0.*)',
    'Code style'
]
# 1 hour timeout
timeout-sec = 3600
